-- CONFIGURATION
INSERT INTO TA_GLOBAL_CONFIGURATION(first_configured) VALUES(true);
-- VIRTUAL MACHINE TYPE COMMAND
INSERT INTO TA_VIRTUAL_MACHINE_TYPE_COMMAND(ID_VIRTUAL_MACHINE_TYPE_COMMAND, command_value) VALUES('java', 'java');
-- VIRTUAL MACHINE TYPE COMMAND ARG
INSERT INTO TA_VIRTUAL_MACHINE_TYPE_COMMAND_ARG(arg_name, arg_value, ID_VIRTUAL_MACHINE_TYPE_COMMAND) VALUES('-version', '', 'java');
-- VIRTUAL MACHINE TYPE
INSERT INTO TA_VIRTUAL_MACHINE_TYPE(name, ID_VIRTUAL_MACHINE_TYPE_COMMAND) VALUES('java', 'java');
-- VIRTUAL MACHINE
INSERT INTO TA_VIRTUAL_MACHINE(name, id_virtual_machine_type) VALUES('virtualMachineTest1', 1);